### ISSUE TITLE
404 when going to localhost:3000

### ISSUE THREAD

**Issue by AnishDe12020** [timcole/sugma#1]
I was just trying this project and built it locally (following the guide in [`README.md`](https://github.com/timcole/sugma/blob/main/README.md#build-it-yourself) and ran `npm start` and then I get the following 404 page - 

![image](https://user-images.githubusercontent.com/63192115/127605056-ba3423c3-1ef0-41fb-9a84-1a740a99cfdb.png)

I would like to know if I went wrong in any step or if it is a bug, I hope it is fixed soon!!!

**Comment by timcole** [comment]
SUGMA requires using CF Access for authentication. You're getting redirected to `/cdn-cgi/access/logout` (CF Access' logout page) because you don't have a valid auth token.

To dev locally though cloudflare, look at Cloudflare Argo Tunnel with cloudflared.
Example: https://developers.cloudflare.com/cloudflare-one/tutorials/share-new-site
